[theme] 
name = "native"

[icons]
name = "material-nf"

[[block]]
block = "backlight"
cycle = [100, 75, 50, 25, 0, 25, 50, 75]
format = "{brightness}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "free"
format = "HDD{used}/{total}"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]

[[block]]
block = "net"
format = "{ssid} {ip} {speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"


[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 1
format = "%D %r"
